In [ ]:
#Taskk 1: 
import numpy as np

# Create a random array for demonstration
x = np.random.randint(1, 10, size=10)
print("Original array:")
print(x)

# Change the sign of elements between 3 and 8
x[(x > 3) & (x < 8)] *= -1

print("\nModified array:")
print(x)

Original array:
[8 4 1 6 3 4 1 9 7 6]

Modified array:
[ 8 -4  1 -6  3 -4  1  9 -7 -6]


In [ ]:
#Task 2: Replace the maximum element of a random array with 0
import numpy as np

# Create a random array for demonstration
x = np.random.randint(1, 100, size=10)
print("Original array:")
print(x)

# Find the index of the maximum element
max_index = np.argmax(x)

# Replace the max element with 0
x[max_index] = 0

print("\nModified array:")
print(x)

Original array:
[31 15 86 54 95 10 23 37 22 75]

Modified array:
[31 15 86 54  0 10 23 37 22 75]


In [ ]:
#Task 3: Calculate the outer product of two arrays
import numpy as np

# Create two arrays for demonstration
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Calculate the outer product
outer_product = np.outer(x, y)

print("Outer product:")
print(outer_product)

Outer product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [7]:
#Task 4: Find rows in A that contain elements from each row in B
import numpy as np

# Create sample arrays A and B
A = np.random.randint(0, 5, size=(8, 3))
B = np.random.randint(0, 5, size=(2, 2))
print("Array A:")
print(A)
print("\nArray B:")
print(B)

# Convert B rows to sorted tuples for easy comparison
B_sorted = np.sort(B, axis=1)
matching_rows = []

for row_a in A:
    is_match = False
    for row_b in B_sorted:
        # Check if all elements of sorted B row are present in sorted A row
        if np.all(np.in1d(row_b, row_a)):
            is_match = True
            break
    if is_match:
        matching_rows.append(row_a)

print("\nRows in A that contain elements from each row in B:")
print(np.unique(matching_rows, axis=0))

Array A:
[[4 0 0]
 [0 4 2]
 [3 0 3]
 [2 2 2]
 [1 4 3]
 [4 2 2]
 [1 4 1]
 [2 0 0]]

Array B:
[[3 0]
 [4 4]]

Rows in A that contain elements from each row in B:
[[0 4 2]
 [1 4 1]
 [1 4 3]
 [3 0 3]
 [4 0 0]
 [4 2 2]]


C:\Users\CEM\AppData\Local\Temp\ipykernel_7348\821814479.py:20: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  if np.all(np.in1d(row_b, row_a)):


In [8]:
#Task 5: From a 10x3 matrix, find rows with unequal values
import numpy as np

# Create a 10x3 matrix for demonstration
matrix = np.array([[1, 2, 3], [4, 4, 4], [5, 6, 7], [8, 8, 8], [9, 9, 9], [1, 5, 3], [4, 5, 6], [7, 8, 9], [1, 1, 1], [2, 3, 4]])
print("Original matrix:")
print(matrix)

# Find rows where not all values are equal
unique_rows = matrix[np.apply_along_axis(lambda x: len(np.unique(x)) > 1, 1, matrix)]

print("\nRows with unequal values:")
print(unique_rows)

Original matrix:
[[1 2 3]
 [4 4 4]
 [5 6 7]
 [8 8 8]
 [9 9 9]
 [1 5 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]
 [2 3 4]]

Rows with unequal values:
[[1 2 3]
 [5 6 7]
 [1 5 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]


In [9]:
#Task 6: Delete duplicate rows from a 2D array
import numpy as np

# Create a 2D array with duplicate rows
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])
print("Original array:")
print(array)

# Delete duplicate rows
unique_array = np.unique(array, axis=0)

print("\nArray with duplicate rows removed:")
print(unique_array)

Original array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Array with duplicate rows removed:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Task 7: Calculate the product of non-zero diagonal elements of a matrix without using NumPy
def product_of_nonzero_diagonal_no_numpy(matrix):
    product = 1
    for i in range(len(matrix)):
        if matrix[i][i] != 0:
            product *= matrix[i][i]
    return product

X = [[1, 0, 1], [2, 0, 2], [3, 0, 3]]
print(f"Product of non-zero diagonal elements (without NumPy): {product_of_nonzero_diagonal_no_numpy(X)}")

Product of non-zero diagonal elements (without NumPy): 3


In [11]:
#Task 7: Calculate the product of non-zero diagonal elements of a matrix using NumPy
import numpy as np

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3]])
diagonal_elements = np.diag(X)
nonzero_elements = diagonal_elements[diagonal_elements != 0]
product = np.prod(nonzero_elements)
print(f"Product of non-zero diagonal elements (with NumPy): {product}")

Product of non-zero diagonal elements (with NumPy): 3


In [ ]:
#Task 8: Check if two lists are the same multiset without using NumPy
def same_multiset_no_numpy(x, y):
    return sorted(x) == sorted(y)

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(f"Are x and y the same multiset (without NumPy)? {same_multiset_no_numpy(x, y)}")

In [12]:
#Task 8: Check if two lists are the same multiset using NumPy
import numpy as np

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
same_multiset = np.array_equal(np.sort(x), np.sort(y))
print(f"Are x and y the same multiset (with NumPy)? {same_multiset}")

Are x and y the same multiset (with NumPy)? True


In [1]:
#Task 9: Find the maximum element after a zero in a list without using NumPy
def max_after_zero_no_numpy(x):
    max_element = None
    for i in range(1, len(x)):
        if x[i-1] == 0:
            if max_element is None or x[i] > max_element:
                max_element = x[i]
    return max_element

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(f"Maximum element after a zero (without NumPy): {max_after_zero_no_numpy(x)}")

Maximum element after a zero (without NumPy): 5


In [2]:
#Task 9: Find the maximum element after a zero in a list using NumPy
import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zeros_indices = np.where(x[:-1] == 0)[0]
elements_after_zeros = x[zeros_indices + 1]
max_element = np.max(elements_after_zeros)
print(f"Maximum element after a zero (with NumPy): {max_element}")

Maximum element after a zero (with NumPy): 5


In [3]:
#Task 10: Run-length encoding of a list without using NumPy
def run_length_encoding_no_numpy(x):
    if not x:
        return [], []
    values = []
    counts = []
    current_value = x[0]
    current_count = 1
    for i in range(1, len(x)):
        if x[i] == current_value:
            current_count += 1
        else:
            values.append(current_value)
            counts.append(current_count)
            current_value = x[i]
            current_count = 1
    values.append(current_value)
    counts.append(current_count)
    return values, counts

x = [2, 2, 2, 3, 3, 3, 5]
values, counts = run_length_encoding_no_numpy(x)
print(f"Run-length encoding (without NumPy): (Values: {values}, Counts: {counts})")

Run-length encoding (without NumPy): (Values: [2, 3, 5], Counts: [3, 3, 1])


In [4]:
#Task 10: Run-length encoding of a list using NumPy
import numpy as np

def run_length_encoding_numpy(x):
    x = np.array(x)
    if not x.size:
        return np.array([]), np.array([])
    
    unique_values, indices = np.unique(x, return_index=True)
    split_indices = np.where(x[:-1] != x[1:])[0] + 1
    counts = np.diff(np.concatenate(([0], split_indices, [len(x)])))
    
    return x[indices], counts

x = np.array([2, 2, 2, 3, 3, 3, 5])
values, counts = run_length_encoding_numpy(x)
print(f"Run-length encoding (with NumPy): (Values: {values}, Counts: {counts})")

Run-length encoding (with NumPy): (Values: [2 3 5], Counts: [3 3 1])


In [5]:
#Task 11: Calculate the Euclidean distance matrix between two sets of points without using NumPy
def euclidean_distance_no_numpy(X, Y):
    matrix = []
    for x_row in X:
        row = []
        for y_row in Y:
            dist_sq = sum([(x_row[i] - y_row[i])**2 for i in range(len(x_row))])
            row.append(dist_sq**0.5)
        matrix.append(row)
    return matrix

X = [[1, 2], [3, 4]]
Y = [[5, 6], [7, 8]]
print(f"Euclidean distance matrix (without NumPy): {euclidean_distance_no_numpy(X, Y)}")

Euclidean distance matrix (without NumPy): [[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]


In [6]:
#Task 11: Calculate the Euclidean distance matrix between two sets of points using NumPy and SciPy
import numpy as np
from scipy.spatial.distance import cdist

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

# Using a manual calculation
distances = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=-1))
print("Euclidean distance matrix (manual NumPy):")
print(distances)

# Using scipy.spatial.distance.cdist for comparison
cdist_distances = cdist(X, Y, 'euclidean')
print("\nEuclidean distance matrix (using cdist):")
print(cdist_distances)

Euclidean distance matrix (manual NumPy):
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]

Euclidean distance matrix (using cdist):
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]
